[versions]
kotlin = "1.9.23"
intellij = "1.17.3"
kotlinter = "4.3.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
